### ISSUE TITLE
The navigation menu disappears when entering the Crisis Room (since OpenKAT v1.5)

### ISSUE THREAD

**Issue by Darwinkel** [minvws/nl-kat-rocky#165]
**Is your feature request related to a problem? Please describe.**
The navigation menu disappears when entering the Crisis Room. I understand that this is because the Crisis Room is not bound to a specific organisation, but it feels clumsy and unrefined from an UI/UX perspective that there is no context/info/hint provided.

**Describe the solution you'd like**
The navigation menu itself should probably be redesigned/overhauled. I'm not sure what a good short term fix for this issue would be, but adding some context/info/UX hint about the Crisis Room being distinct from the other nav menu entries would be a good start.

**Describe alternatives you've considered**
A seasoned KAT user will probably not mind too much, although the cost of a misclick is high: it takes multiple clicks to recover from the Crisis Room back to another page.

**Comment by TwistMeister** [comment]
Fair point, design-wise this is already being addressed in https://github.com/minvws/nl-kat-rocky/issues/138

**Comment by underdarknl** [comment]
Once a user is in the Crisis room. they are no longer 'in' a specific organization. Because of this the cannot click to various of the lists/objects/katalogus that only make sense inside a specific organization scope.
Maybe we can reintroduce them with an overreaching 'all organization' or 'selected organizations' scope later.

**Comment by HeleenSG** [comment]
I expect that down the line there will be use for the same/these pages within the overarching scope. 

For instance, the object page without the scope of the organisation could still show objects which the account has access to. Which could help users navigate to a specific object without knowing in which organisation it belongs to. For example obscure-object-name.nl could be found by searching within the object page on the top level. 

But that will introduce a number of issues that we need to think about/check. For instance is it technically possible to search within all objects? As this set could be huge. 

Doing recurring tasks on multiple organisations would also be a use case I expect to arise. For example enabling the same boefje on multiple organisations. Which means it would make sense for the katalogus to be on the top level as well. Outside of any specific organisation scope. This has its own challenges around setting/approving clearance levels. So that is one that we should think through and design as well.

So I think it's best to discuss the technical limitations before we implement this into the design. But I do agree with you that the current situation can be unexpected and confusing. And as @TwistMeister mentioned a new design is scheduled.
